import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { createTheme, MantineProvider } from '@mantine/core'
import './globals.css'
import '@mantine/core/styles.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const theme = createTheme({
  /** Put your mantine theme override here */
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MantineProvider theme={theme}>
          <div className="bg-[#f8f9fa] min-h-[100vh]">{children}</div>
        </MantineProvider>
      </body>
    </html>
  )
}
