import type { Metadata } from 'next'
import { MantineProvider } from '@mantine/core'
import { Header } from '@/components/Header/Header'

import './globals.css'
import '@mantine/core/styles.css'

export const metadata: Metadata = {
  title: 'MBA Methods',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/favicon.ico" />
      </head>
      <body>
        <MantineProvider>
          <Header />
          <main className="min-h-screen flex-col items-center justify-between px-24 py-10 w-full bg-main text-main">
            {children}
          </main>
        </MantineProvider>
      </body>
    </html>
  )
}
